// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6bU9DSp1rQ8PhRBVPRkLKjvZpOzOZfWw',
    appId: '1:82251307223:web:691980817658e93379f892',
    messagingSenderId: '82251307223',
    projectId: 'skill-bridge-ai-c02ef',
    authDomain: 'skill-bridge-ai-c02ef.firebaseapp.com',
    storageBucket: 'skill-bridge-ai-c02ef.firebasestorage.app',
    measurementId: 'G-X95B3CZ3XZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGBNJDfSsfSSgjhVftYHi-jTdEl6fiER8',
    appId: '1:82251307223:android:afc865c147553ee779f892',
    messagingSenderId: '82251307223',
    projectId: 'skill-bridge-ai-c02ef',
    storageBucket: 'skill-bridge-ai-c02ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAzLkb9Is-XBn_laIuBzPXkB5fdCyhl2E',
    appId: '1:82251307223:ios:f8c3b441b362c81e79f892',
    messagingSenderId: '82251307223',
    projectId: 'skill-bridge-ai-c02ef',
    storageBucket: 'skill-bridge-ai-c02ef.firebasestorage.app',
    iosBundleId: 'com.skillbrdgeai.app',
  );
}
